### ISSUE TITLE
Feature Request: Call with gRPC Plugin

### ISSUE THREAD

**Issue by cyberjacob** [halotron/ProtobufGenerator#1]
Optionally calling protoc with the `--grpc_out={outdir}` and `--plugin=protoc-gen-grpc="C:\path\to\grpc_csharp_plugin.exe"` would allow the tool to generate the necessary classes for [gRPC](https://grpc.io/) integration.

**Comment by halotron** [comment]
Thanks, Interesting idea!
So the only thing needed is 
"C:\path\to\grpc_csharp_plugin.exe"
locally?

I will definitely look into it, but PR is welcome as well ;-)

**Comment by cyberjacob** [comment]
It's included with the `grpc.tools` package if that helps (Which also has `protoc.exe`). I've never worked with a `BaseCodeGeneratorWithSite` before (Don't have much C# experience in general) but had a quick look, however I couldn't work out how to make it return two files.

**Comment by jasells** [comment]
adding a UI under Tools->Options->ProtoBufGenerator or the like would allow for users to provide option params to protoc.exe.

Another useful pram is: --csharp_opt=file_extension=.g.c  which makes the generated files look like CsharGenCode.g.cs.  It is a common patter for code generators to use the '.g.cs' extension for clarity of what code is generated vs. manually written.  I was hoping this extension would work for me, but alas, it will not since I am also using gRPC.  

I will have to stick to the pre-build .bat file method until I or some on else has time to look into adding some for of support.

**Comment by halotron** [comment]
Excellent, thanks!
I cannot do the merge now, but will do it asap.

That UI sounds like a good idea.

//Jonas


2018-06-25 16:23 GMT+02:00 jasells <notifications@github.com>:

**Comment by halotron** [comment]
grpc is possible now
